C:\CAA\Code\DimensionWeldWithMouse\.\CAADraftingInterfaces\various\win_b64\HList\PrivateInterfaces.hl
C:\CAA\Code\DimensionWeldWithMouse\.\CAADraftingInterfaces\various\win_b64\HList\ProtectedInterfaces.hl
C:\CAA\Code\DimensionWeldWithMouse\.\CAADraftingInterfaces\various\win_b64\HList\PublicInterfaces.hl
C:\CATIA\DassaultSystemes\B19\.\AdvancedMathematics\various\win_b64\HList\ProtectedInterfaces.hl
C:\CATIA\DassaultSystemes\B19\.\AdvancedMathematics\various\win_b64\HList\PublicInterfaces.hl
C:\CATIA\DassaultSystemes\B19\.\AdvancedTopologicalOpe\various\win_b64\HList\ProtectedInterfaces.hl
C:\CATIA\DassaultSystemes\B19\.\AdvancedTopologicalOpe\various\win_b64\HList\PublicInterfaces.hl
C:\CATIA\DassaultSystemes\B19\.\ApplicationFrame\various\win_b64\HList\ProtectedInterfaces.hl
C:\CATIA\DassaultSystemes\B19\.\ApplicationFrame\various\win_b64\HList\PublicInterfaces.hl
C:\CATIA\DassaultSystemes\B19\.\AutomationInterfaces\various\win_b64\HList\ProtectedInterfaces.hl
C:\CATIA\DassaultSystemes\B19\.\AutomationInterfaces\various\win_b64\HList\PublicInterfaces.hl
C:\CATIA\DassaultSystemes\B19\.\BasicTopologicalOpe\various\win_b64\HList\ProtectedInterfaces.hl
C:\CATIA\DassaultSystemes\B19\.\BasicTopologicalOpe\various\win_b64\HList\PublicInterfaces.hl
C:\CATIA\DassaultSystemes\B19\.\BatchInfrastructure\various\win_b64\HList\ProtectedInterfaces.hl
C:\CATIA\DassaultSystemes\B19\.\BatchInfrastructure\various\win_b64\HList\PublicInterfaces.hl
C:\CATIA\DassaultSystemes\B19\.\CAT3DXmlInterfaces\various\win_b64\HList\ProtectedInterfaces.hl
C:\CATIA\DassaultSystemes\B19\.\CAT3DXmlInterfaces\various\win_b64\HList\PublicInterfaces.hl
C:\CATIA\DassaultSystemes\B19\.\CATAssemblyInterfaces\various\win_b64\HList\ProtectedInterfaces.hl
C:\CATIA\DassaultSystemes\B19\.\CATAssemblyInterfaces\various\win_b64\HList\PublicInterfaces.hl
C:\CATIA\DassaultSystemes\B19\.\CATCDS\various\win_b64\HList\ProtectedInterfaces.hl
C:\CATIA\DassaultSystemes\B19\.\CATCDS\various\win_b64\HList\PublicInterfaces.hl
C:\CATIA\DassaultSystemes\B19\.\CATCDSUtilities\various\win_b64\HList\ProtectedInterfaces.hl
C:\CATIA\DassaultSystemes\B19\.\CATCDSUtilities\various\win_b64\HList\PublicInterfaces.hl
C:\CATIA\DassaultSystemes\B19\.\CATCloudBasicResources\various\win_b64\HList\ProtectedInterfaces.hl
C:\CATIA\DassaultSystemes\B19\.\CATCloudBasicResources\various\win_b64\HList\PublicInterfaces.hl
C:\CATIA\DassaultSystemes\B19\.\CATDataCompatibilityInfra\various\win_b64\HList\ProtectedInterfaces.hl
C:\CATIA\DassaultSystemes\B19\.\CATDataCompatibilityInfra\various\win_b64\HList\PublicInterfaces.hl
C:\CATIA\DassaultSystemes\B19\.\CATElfiniOpenSoftware\various\win_b64\HList\ProtectedInterfaces.hl
C:\CATIA\DassaultSystemes\B19\.\CATElfiniOpenSoftware\various\win_b64\HList\PublicInterfaces.hl
C:\CATIA\DassaultSystemes\B19\.\CATFuzzyOperators\various\win_b64\HList\ProtectedInterfaces.hl
C:\CATIA\DassaultSystemes\B19\.\CATFuzzyOperators\various\win_b64\HList\PublicInterfaces.hl
C:\CATIA\DassaultSystemes\B19\.\CATGraphicProperties\various\win_b64\HList\ProtectedInterfaces.hl
C:\CATIA\DassaultSystemes\B19\.\CATGraphicProperties\various\win_b64\HList\PublicInterfaces.hl
C:\CATIA\DassaultSystemes\B19\.\CATIAApplicationFrame\various\win_b64\HList\ProtectedInterfaces.hl
C:\CATIA\DassaultSystemes\B19\.\CATIAApplicationFrame\various\win_b64\HList\PublicInterfaces.hl
C:\CATIA\DassaultSystemes\B19\.\CATIADataBasics\various\win_b64\HList\ProtectedInterfaces.hl
C:\CATIA\DassaultSystemes\B19\.\CATIADataBasics\various\win_b64\HList\PublicInterfaces.hl
C:\CATIA\DassaultSystemes\B19\.\CATIADataMacFortran\various\win_b64\HList\ProtectedInterfaces.hl
C:\CATIA\DassaultSystemes\B19\.\CATIADataMacFortran\various\win_b64\HList\PublicInterfaces.hl
C:\CATIA\DassaultSystemes\B19\.\CATImmWtpInterfaces\various\win_b64\HList\ProtectedInterfaces.hl
C:\CATIA\DassaultSystemes\B19\.\CATImmWtpInterfaces\various\win_b64\HList\PublicInterfaces.hl
C:\CATIA\DassaultSystemes\B19\.\CATJavaBridge\various\win_b64\HList\ProtectedInterfaces.hl
C:\CATIA\DassaultSystemes\B19\.\CATJavaBridge\various\win_b64\HList\PublicInterfaces.hl
C:\CATIA\DassaultSystemes\B19\.\CATPDMBaseInterfaces\various\win_b64\HList\ProtectedInterfaces.hl
C:\CATIA\DassaultSystemes\B19\.\CATPDMBaseInterfaces\various\win_b64\HList\PublicInterfaces.hl
C:\CATIA\DassaultSystemes\B19\.\CATPLMDictionary\various\win_b64\HList\ProtectedInterfaces.hl
C:\CATIA\DassaultSystemes\B19\.\CATPLMDictionary\various\win_b64\HList\PublicInterfaces.hl
C:\CATIA\DassaultSystemes\B19\.\CATShmInterfaces\various\win_b64\HList\ProtectedInterfaces.hl
C:\CATIA\DassaultSystemes\B19\.\CATShmInterfaces\various\win_b64\HList\PublicInterfaces.hl
C:\CATIA\DassaultSystemes\B19\.\CATSmarTeamIntegInterfaces\various\win_b64\HList\ProtectedInterfaces.hl
C:\CATIA\DassaultSystemes\B19\.\CATSmarTeamIntegInterfaces\various\win_b64\HList\PublicInterfaces.hl
C:\CATIA\DassaultSystemes\B19\.\CATSubdivisionApproximation\various\win_b64\HList\ProtectedInterfaces.hl
C:\CATIA\DassaultSystemes\B19\.\CATSubdivisionApproximation\various\win_b64\HList\PublicInterfaces.hl
C:\CATIA\DassaultSystemes\B19\.\CATSubdivisionMeshOperators\various\win_b64\HList\ProtectedInterfaces.hl
C:\CATIA\DassaultSystemes\B19\.\CATSubdivisionMeshOperators\various\win_b64\HList\PublicInterfaces.hl
C:\CATIA\DassaultSystemes\B19\.\CATSubdivisionObjects\various\win_b64\HList\ProtectedInterfaces.hl
C:\CATIA\DassaultSystemes\B19\.\CATSubdivisionObjects\various\win_b64\HList\PublicInterfaces.hl
C:\CATIA\DassaultSystemes\B19\.\CATTPSInterfaces\various\win_b64\HList\PublicInterfaces.hl
C:\CATIA\DassaultSystemes\B19\.\CATTTRSInterfaces\various\win_b64\HList\ProtectedInterfaces.hl
C:\CATIA\DassaultSystemes\B19\.\CATTTRSInterfaces\various\win_b64\HList\PublicInterfaces.hl
C:\CATIA\DassaultSystemes\B19\.\CATTechResultInterfaces\various\win_b64\HList\ProtectedInterfaces.hl
C:\CATIA\DassaultSystemes\B19\.\CATTechResultInterfaces\various\win_b64\HList\PublicInterfaces.hl
C:\CATIA\DassaultSystemes\B19\.\CATTechnologicalPackageUIItf\various\win_b64\HList\ProtectedInterfaces.hl
C:\CATIA\DassaultSystemes\B19\.\CATTechnologicalPackageUIItf\various\win_b64\HList\PublicInterfaces.hl
C:\CATIA\DassaultSystemes\B19\.\CATV4System\various\win_b64\HList\ProtectedInterfaces.hl
C:\CATIA\DassaultSystemes\B19\.\CATV4System\various\win_b64\HList\PublicInterfaces.hl
C:\CATIA\DassaultSystemes\B19\.\CATVirtualVaultSystem\various\win_b64\HList\ProtectedInterfaces.hl
C:\CATIA\DassaultSystemes\B19\.\CATVirtualVaultSystem\various\win_b64\HList\PublicInterfaces.hl
C:\CATIA\DassaultSystemes\B19\.\CATWBx\various\win_b64\HList\ProtectedInterfaces.hl
C:\CATIA\DassaultSystemes\B19\.\CATWBx\various\win_b64\HList\PublicInterfaces.hl
C:\CATIA\DassaultSystemes\B19\.\CATXDocLinkInterfaces\various\win_b64\HList\ProtectedInterfaces.hl
C:\CATIA\DassaultSystemes\B19\.\CATXDocLinkInterfaces\various\win_b64\HList\PublicInterfaces.hl
C:\CATIA\DassaultSystemes\B19\.\CGMV5Interoperability\various\win_b64\HList\ProtectedInterfaces.hl
C:\CATIA\DassaultSystemes\B19\.\CGMV5Interoperability\various\win_b64\HList\PublicInterfaces.hl
C:\CATIA\DassaultSystemes\B19\.\Communications\various\win_b64\HList\ProtectedInterfaces.hl
C:\CATIA\DassaultSystemes\B19\.\Communications\various\win_b64\HList\PublicInterfaces.hl
C:\CATIA\DassaultSystemes\B19\.\ComponentsCatalogsInterfaces\various\win_b64\HList\ProtectedInterfaces.hl
C:\CATIA\DassaultSystemes\B19\.\ComponentsCatalogsInterfaces\various\win_b64\HList\PublicInterfaces.hl
C:\CATIA\DassaultSystemes\B19\.\ConstraintModelerInterfaces\various\win_b64\HList\ProtectedInterfaces.hl
C:\CATIA\DassaultSystemes\B19\.\ConstraintModelerInterfaces\various\win_b64\HList\PublicInterfaces.hl
C:\CATIA\DassaultSystemes\B19\.\ConstraintSolver\various\win_b64\HList\ProtectedInterfaces.hl
C:\CATIA\DassaultSystemes\B19\.\ConstraintSolver\various\win_b64\HList\PublicInterfaces.hl
C:\CATIA\DassaultSystemes\B19\.\CurveBasedGeoOperators\various\win_b64\HList\ProtectedInterfaces.hl
C:\CATIA\DassaultSystemes\B19\.\CurveBasedGeoOperators\various\win_b64\HList\PublicInterfaces.hl
C:\CATIA\DassaultSystemes\B19\.\CurveBasedInfrastructure\various\win_b64\HList\ProtectedInterfaces.hl
C:\CATIA\DassaultSystemes\B19\.\CurveBasedInfrastructure\various\win_b64\HList\PublicInterfaces.hl
C:\CATIA\DassaultSystemes\B19\.\CurveBasedMathematics\various\win_b64\HList\ProtectedInterfaces.hl
C:\CATIA\DassaultSystemes\B19\.\CurveBasedMathematics\various\win_b64\HList\PublicInterfaces.hl
C:\CATIA\DassaultSystemes\B19\.\CurveBasedTopoOperators\various\win_b64\HList\ProtectedInterfaces.hl
C:\CATIA\DassaultSystemes\B19\.\CurveBasedTopoOperators\various\win_b64\HList\PublicInterfaces.hl
C:\CATIA\DassaultSystemes\B19\.\DCM3D\various\win_b64\HList\ProtectedInterfaces.hl
C:\CATIA\DassaultSystemes\B19\.\DCM3D\various\win_b64\HList\PublicInterfaces.hl
C:\CATIA\DassaultSystemes\B19\.\Dialog\various\win_b64\HList\ProtectedInterfaces.hl
C:\CATIA\DassaultSystemes\B19\.\Dialog\various\win_b64\HList\PublicInterfaces.hl
C:\CATIA\DassaultSystemes\B19\.\DialogEngine\various\win_b64\HList\ProtectedInterfaces.hl
C:\CATIA\DassaultSystemes\B19\.\DialogEngine\various\win_b64\HList\PublicInterfaces.hl
C:\CATIA\DassaultSystemes\B19\.\DraftingInterfaces\various\win_b64\HList\ProtectedInterfaces.hl
C:\CATIA\DassaultSystemes\B19\.\DraftingInterfaces\various\win_b64\HList\PublicInterfaces.hl
C:\CATIA\DassaultSystemes\B19\.\FileMenu\various\win_b64\HList\ProtectedInterfaces.hl
C:\CATIA\DassaultSystemes\B19\.\FileMenu\various\win_b64\HList\PublicInterfaces.hl
C:\CATIA\DassaultSystemes\B19\.\FreeFormOperators\various\win_b64\HList\ProtectedInterfaces.hl
C:\CATIA\DassaultSystemes\B19\.\FreeFormOperators\various\win_b64\HList\PublicInterfaces.hl
C:\CATIA\DassaultSystemes\B19\.\GSMInterfaces\various\win_b64\HList\ProtectedInterfaces.hl
C:\CATIA\DassaultSystemes\B19\.\GSMInterfaces\various\win_b64\HList\PublicInterfaces.hl
C:\CATIA\DassaultSystemes\B19\.\GenericNaming\various\win_b64\HList\PrivateInterfaces.hl
C:\CATIA\DassaultSystemes\B19\.\GenericNaming\various\win_b64\HList\ProtectedInterfaces.hl
C:\CATIA\DassaultSystemes\B19\.\GenericNaming\various\win_b64\HList\PublicInterfaces.hl
C:\CATIA\DassaultSystemes\B19\.\GeometricObjects\various\win_b64\HList\ProtectedInterfaces.hl
C:\CATIA\DassaultSystemes\B19\.\GeometricObjects\various\win_b64\HList\PublicInterfaces.hl
C:\CATIA\DassaultSystemes\B19\.\GeometricObjectsCGM\various\win_b64\HList\ProtectedInterfaces.hl
C:\CATIA\DassaultSystemes\B19\.\GeometricObjectsCGM\various\win_b64\HList\PublicInterfaces.hl
C:\CATIA\DassaultSystemes\B19\.\GeometricOperators\various\win_b64\HList\ProtectedInterfaces.hl
C:\CATIA\DassaultSystemes\B19\.\GeometricOperators\various\win_b64\HList\PublicInterfaces.hl
C:\CATIA\DassaultSystemes\B19\.\GeometryVisualization\various\win_b64\HList\ProtectedInterfaces.hl
C:\CATIA\DassaultSystemes\B19\.\GeometryVisualization\various\win_b64\HList\PublicInterfaces.hl
C:\CATIA\DassaultSystemes\B19\.\Graph\various\win_b64\HList\ProtectedInterfaces.hl
C:\CATIA\DassaultSystemes\B19\.\Graph\various\win_b64\HList\PublicInterfaces.hl
C:\CATIA\DassaultSystemes\B19\.\HLRBase\various\win_b64\HList\ProtectedInterfaces.hl
C:\CATIA\DassaultSystemes\B19\.\HLRBase\various\win_b64\HList\PublicInterfaces.hl
C:\CATIA\DassaultSystemes\B19\.\InfInterfaces\various\win_b64\HList\ProtectedInterfaces.hl
C:\CATIA\DassaultSystemes\B19\.\InfInterfaces\various\win_b64\HList\PublicInterfaces.hl
C:\CATIA\DassaultSystemes\B19\.\InteractiveInterfaces\various\win_b64\HList\ProtectedInterfaces.hl
C:\CATIA\DassaultSystemes\B19\.\InteractiveInterfaces\various\win_b64\HList\PublicInterfaces.hl
C:\CATIA\DassaultSystemes\B19\.\KnowledgeInterfaces\various\win_b64\HList\ProtectedInterfaces.hl
C:\CATIA\DassaultSystemes\B19\.\KnowledgeInterfaces\various\win_b64\HList\PublicInterfaces.hl
C:\CATIA\DassaultSystemes\B19\.\KnowledgeModeler\various\win_b64\HList\ProtectedInterfaces.hl
C:\CATIA\DassaultSystemes\B19\.\KnowledgeModeler\various\win_b64\HList\PublicInterfaces.hl
C:\CATIA\DassaultSystemes\B19\.\LiteralFeatures\various\win_b64\HList\ProtectedInterfaces.hl
C:\CATIA\DassaultSystemes\B19\.\LiteralFeatures\various\win_b64\HList\PublicInterfaces.hl
C:\CATIA\DassaultSystemes\B19\.\Mainwin\various\win_b64\HList\ProtectedInterfaces.hl
C:\CATIA\DassaultSystemes\B19\.\Mainwin\various\win_b64\HList\PublicInterfaces.hl
C:\CATIA\DassaultSystemes\B19\.\Mathematics\various\win_b64\HList\ProtectedInterfaces.hl
C:\CATIA\DassaultSystemes\B19\.\Mathematics\various\win_b64\HList\PublicInterfaces.hl
C:\CATIA\DassaultSystemes\B19\.\MeasureGeometryInterfaces\various\win_b64\HList\ProtectedInterfaces.hl
C:\CATIA\DassaultSystemes\B19\.\MeasureGeometryInterfaces\various\win_b64\HList\PublicInterfaces.hl
C:\CATIA\DassaultSystemes\B19\.\MecModInterfaces\various\win_b64\HList\ProtectedInterfaces.hl
C:\CATIA\DassaultSystemes\B19\.\MecModInterfaces\various\win_b64\HList\PublicInterfaces.hl
C:\CATIA\DassaultSystemes\B19\.\MechanicalCommands\various\win_b64\HList\ProtectedInterfaces.hl
C:\CATIA\DassaultSystemes\B19\.\MechanicalCommands\various\win_b64\HList\PublicInterfaces.hl
C:\CATIA\DassaultSystemes\B19\.\MechanicalModeler\various\win_b64\HList\PublicInterfaces.hl
C:\CATIA\DassaultSystemes\B19\.\Multimedia\various\win_b64\HList\ProtectedInterfaces.hl
C:\CATIA\DassaultSystemes\B19\.\Multimedia\various\win_b64\HList\PublicInterfaces.hl
C:\CATIA\DassaultSystemes\B19\.\NewTopologicalObjects\various\win_b64\HList\PrivateInterfaces.hl
C:\CATIA\DassaultSystemes\B19\.\NewTopologicalObjects\various\win_b64\HList\ProtectedInterfaces.hl
C:\CATIA\DassaultSystemes\B19\.\NewTopologicalObjects\various\win_b64\HList\PublicInterfaces.hl
C:\CATIA\DassaultSystemes\B19\.\ObjectModelerBase\various\win_b64\HList\PrivateInterfaces.hl
C:\CATIA\DassaultSystemes\B19\.\ObjectModelerBase\various\win_b64\HList\ProtectedInterfaces.hl
C:\CATIA\DassaultSystemes\B19\.\ObjectModelerBase\various\win_b64\HList\PublicInterfaces.hl
C:\CATIA\DassaultSystemes\B19\.\ObjectModelerBaseUI\various\win_b64\HList\ProtectedInterfaces.hl
C:\CATIA\DassaultSystemes\B19\.\ObjectModelerBaseUI\various\win_b64\HList\PublicInterfaces.hl
C:\CATIA\DassaultSystemes\B19\.\ObjectModelerCATIA\various\win_b64\HList\ProtectedInterfaces.hl
C:\CATIA\DassaultSystemes\B19\.\ObjectModelerCATIA\various\win_b64\HList\PublicInterfaces.hl
C:\CATIA\DassaultSystemes\B19\.\ObjectModelerCollection\various\win_b64\HList\PrivateInterfaces.hl
C:\CATIA\DassaultSystemes\B19\.\ObjectModelerCollection\various\win_b64\HList\ProtectedInterfaces.hl
C:\CATIA\DassaultSystemes\B19\.\ObjectModelerCollection\various\win_b64\HList\PublicInterfaces.hl
C:\CATIA\DassaultSystemes\B19\.\ObjectModelerInterfaces\various\win_b64\HList\ProtectedInterfaces.hl
C:\CATIA\DassaultSystemes\B19\.\ObjectModelerInterfaces\various\win_b64\HList\PublicInterfaces.hl
C:\CATIA\DassaultSystemes\B19\.\ObjectModelerNavigator\various\win_b64\HList\ProtectedInterfaces.hl
C:\CATIA\DassaultSystemes\B19\.\ObjectModelerNavigator\various\win_b64\HList\PublicInterfaces.hl
C:\CATIA\DassaultSystemes\B19\.\ObjectModelerSystem\various\win_b64\HList\ProtectedInterfaces.hl
C:\CATIA\DassaultSystemes\B19\.\ObjectModelerSystem\various\win_b64\HList\PublicInterfaces.hl
C:\CATIA\DassaultSystemes\B19\.\ObjectSpecsModeler\various\win_b64\HList\ProtectedInterfaces.hl
C:\CATIA\DassaultSystemes\B19\.\ObjectSpecsModeler\various\win_b64\HList\PublicInterfaces.hl
C:\CATIA\DassaultSystemes\B19\.\PartInterfaces\various\win_b64\HList\ProtectedInterfaces.hl
C:\CATIA\DassaultSystemes\B19\.\PartInterfaces\various\win_b64\HList\PublicInterfaces.hl
C:\CATIA\DassaultSystemes\B19\.\PolygonalTools\various\win_b64\HList\ProtectedInterfaces.hl
C:\CATIA\DassaultSystemes\B19\.\PolygonalTools\various\win_b64\HList\PublicInterfaces.hl
C:\CATIA\DassaultSystemes\B19\.\PolyhedralInterfaces\various\win_b64\HList\ProtectedInterfaces.hl
C:\CATIA\DassaultSystemes\B19\.\PolyhedralInterfaces\various\win_b64\HList\PublicInterfaces.hl
C:\CATIA\DassaultSystemes\B19\.\PolyhedralMathematics\various\win_b64\HList\ProtectedInterfaces.hl
C:\CATIA\DassaultSystemes\B19\.\PolyhedralMathematics\various\win_b64\HList\PublicInterfaces.hl
C:\CATIA\DassaultSystemes\B19\.\PolyhedralObjects\various\win_b64\HList\ProtectedInterfaces.hl
C:\CATIA\DassaultSystemes\B19\.\PolyhedralObjects\various\win_b64\HList\PublicInterfaces.hl
C:\CATIA\DassaultSystemes\B19\.\PolyhedralOperators\various\win_b64\HList\ProtectedInterfaces.hl
C:\CATIA\DassaultSystemes\B19\.\PolyhedralOperators\various\win_b64\HList\PublicInterfaces.hl
C:\CATIA\DassaultSystemes\B19\.\PolyhedralVisuOperators\various\win_b64\HList\ProtectedInterfaces.hl
C:\CATIA\DassaultSystemes\B19\.\PolyhedralVisuOperators\various\win_b64\HList\PublicInterfaces.hl
C:\CATIA\DassaultSystemes\B19\.\PolyhedralVisualization\various\win_b64\HList\ProtectedInterfaces.hl
C:\CATIA\DassaultSystemes\B19\.\PolyhedralVisualization\various\win_b64\HList\PublicInterfaces.hl
C:\CATIA\DassaultSystemes\B19\.\Print\various\win_b64\HList\ProtectedInterfaces.hl
C:\CATIA\DassaultSystemes\B19\.\Print\various\win_b64\HList\PublicInterfaces.hl
C:\CATIA\DassaultSystemes\B19\.\PrintBase\various\win_b64\HList\ProtectedInterfaces.hl
C:\CATIA\DassaultSystemes\B19\.\PrintBase\various\win_b64\HList\PublicInterfaces.hl
C:\CATIA\DassaultSystemes\B19\.\ProductStructure\various\win_b64\HList\ProtectedInterfaces.hl
C:\CATIA\DassaultSystemes\B19\.\ProductStructure\various\win_b64\HList\PublicInterfaces.hl
C:\CATIA\DassaultSystemes\B19\.\ProductStructureInterfaces\various\win_b64\HList\ProtectedInterfaces.hl
C:\CATIA\DassaultSystemes\B19\.\ProductStructureInterfaces\various\win_b64\HList\PublicInterfaces.hl
C:\CATIA\DassaultSystemes\B19\.\SketcherInterfaces\various\win_b64\HList\ProtectedInterfaces.hl
C:\CATIA\DassaultSystemes\B19\.\SketcherInterfaces\various\win_b64\HList\PublicInterfaces.hl
C:\CATIA\DassaultSystemes\B19\.\SpecialAPI\various\win_b64\HList\ProtectedInterfaces.hl
C:\CATIA\DassaultSystemes\B19\.\SpecialAPI\various\win_b64\HList\PublicInterfaces.hl
C:\CATIA\DassaultSystemes\B19\.\SurfacicGeoOperators\various\win_b64\HList\ProtectedInterfaces.hl
C:\CATIA\DassaultSystemes\B19\.\SurfacicGeoOperators\various\win_b64\HList\PublicInterfaces.hl
C:\CATIA\DassaultSystemes\B19\.\SurfacicInfrastructure\various\win_b64\HList\ProtectedInterfaces.hl
C:\CATIA\DassaultSystemes\B19\.\SurfacicInfrastructure\various\win_b64\HList\PublicInterfaces.hl
C:\CATIA\DassaultSystemes\B19\.\SurfacicMathematics\various\win_b64\HList\ProtectedInterfaces.hl
C:\CATIA\DassaultSystemes\B19\.\SurfacicMathematics\various\win_b64\HList\PublicInterfaces.hl
C:\CATIA\DassaultSystemes\B19\.\SurfacicTopoOperators\various\win_b64\HList\ProtectedInterfaces.hl
C:\CATIA\DassaultSystemes\B19\.\SurfacicTopoOperators\various\win_b64\HList\PublicInterfaces.hl
C:\CATIA\DassaultSystemes\B19\.\System\various\win_b64\HList\ProtectedInterfaces.hl
C:\CATIA\DassaultSystemes\B19\.\System\various\win_b64\HList\PublicInterfaces.hl
C:\CATIA\DassaultSystemes\B19\.\Tessellation\various\win_b64\HList\ProtectedInterfaces.hl
C:\CATIA\DassaultSystemes\B19\.\Tessellation\various\win_b64\HList\PublicInterfaces.hl
C:\CATIA\DassaultSystemes\B19\.\TopologicalOperators\various\win_b64\HList\ProtectedInterfaces.hl
C:\CATIA\DassaultSystemes\B19\.\TopologicalOperators\various\win_b64\HList\PublicInterfaces.hl
C:\CATIA\DassaultSystemes\B19\.\VBA\various\win_b64\HList\ProtectedInterfaces.hl
C:\CATIA\DassaultSystemes\B19\.\VBA\various\win_b64\HList\PublicInterfaces.hl
C:\CATIA\DassaultSystemes\B19\.\Visualization\various\win_b64\HList\ProtectedInterfaces.hl
C:\CATIA\DassaultSystemes\B19\.\Visualization\various\win_b64\HList\PublicInterfaces.hl
C:\CATIA\DassaultSystemes\B19\.\VisualizationBase\various\win_b64\HList\ProtectedInterfaces.hl
C:\CATIA\DassaultSystemes\B19\.\VisualizationBase\various\win_b64\HList\PublicInterfaces.hl
C:\CATIA\DassaultSystemes\B19\.\XMLParser\various\win_b64\HList\ProtectedInterfaces.hl
C:\CATIA\DassaultSystemes\B19\.\XMLParser\various\win_b64\HList\PublicInterfaces.hl
C:\CATIA\DassaultSystemes\B19\.\XlatorCGM\various\win_b64\HList\ProtectedInterfaces.hl
C:\CATIA\DassaultSystemes\B19\.\XlatorCGM\various\win_b64\HList\PublicInterfaces.hl
