set ADL_DB2INSTANCE=DB2
set ADL_DFLT_RULES_LIB=ADLCMCNextArchiRules
set ADL_DIFF_LOCAL=N
set ADL_DIFF_PATH=N/A
set ADL_MERGER="C:\RADER19\intel_a\code\command\ADLMerger2.bat"
set ADL_NLS_LANG=AMERICAN_AMERICA.WE8ISO8859P1
set ADL_ORA_TNS_ADMIN=NA
set ADL_PATH=C:\RADER19\intel_a
set ADL_SITE_NAME=V5R19_B19
set ADL_TMP=C:\TEMP
set ADL_USER_PATH=C:\RADER19\intel_a\code\command
set ALLUSERSPROFILE=C:\ProgramData
set APPDATA=C:\Users\Administrator\AppData\Roaming
set BLD_HOST_OS=win_b64
set CNEXTOUTPUT=console
set CommonProgramFiles=C:\Program Files (x86)\Common Files
set CommonProgramFiles(x86)=C:\Program Files (x86)\Common Files
set CommonProgramW6432=C:\Program Files\Common Files
set COMPUTERNAME=DESKTOP-53K8EVV
set ComSpec=C:\Windows\system32\cmd.exe
set CorbaCppBuildROOT_PATH=\\ds\dsy\iona\Orbix3.3\win_b64
set CorbaCppROOT_PATH=\\ds\dsy\iona\Orbix3.3\win_b64
set CorbaJavaROOT_PATH=\\ds\dsy\iona\Orbix3.3\win_b64
set CSCSkipTestOfMapFileValidity=1
set DriverData=C:\Windows\System32\Drivers\DriverData
set DSarMakerROOT_PATH=C:\RADER19\CATWebDSarMaker
set HOMEDRIVE=C:
set HOMEPATH=\Users\Administrator
set INCLUDE=C:\RADER19\intel_a\.\tools\include\win_b64;C:\RADER19\intel_a\.\tools\include;C:\Program Files (x86)\Microsoft Visual Studio 8\VC\include;C:\Program Files (x86)\Microsoft Visual Studio 8\VC\atlmfc\include;C:\Program Files (x86)\Microsoft Visual Studio 8\VC\PlatformSDK\include
set JLMDeployROOT_PATH=C:\RADER19\intel_a\jlm\jlmdeploy65
set LIB=C:\Program Files\Reference Assemblies\Microsoft\Framework\v3.0;C:\Program Files (x86)\Microsoft Visual Studio 8\VC\lib\amd64;C:\Program Files (x86)\Microsoft Visual Studio 8\VC\atlmfc\lib\amd64;C:\Program Files (x86)\Microsoft Visual Studio 8\VC\PlatformSDK\lib\amd64
set LOCALAPPDATA=C:\Users\Administrator\AppData\Local
set LOGONSERVER=\\DESKTOP-53K8EVV
set mkcsClientMode=1
set mkcsOS_Buildtime=intel_a
set mkcsOS_NAME=Windows_NT
set mkcsOS_Runtime=intel_a
set mkcsROOT_PATH=C:\RADER19\intel_a
set mkcsSHLIB_NAME=PATH
set mkcsSHLIB_PATH=C:\RADER19\intel_a\code\bin
set MkmkADDON_LEVEL=MK_ORBIXCPP33 MK_ORBIXJAVA33 MK_MSCVER=1400
set MkmkADDON_LIB=C:\Program Files\Reference Assemblies\Microsoft\Framework\v3.0;C:\Windows\Microsoft.NET\Framework64\v2.0.50727
set MkmkADDON_PATH=C:\Windows\Microsoft.NET\Framework64\v2.0.50727
set MkmkASPNET20Internal=yes
set MkmkBAD_MINITFLEVEL=4
set mkmkbuild=21901
set MkmkDictionary_PATH=C:\RADER19\intel_a\.\code\dictionary
set MkmkIC_PATH=C:\RADER19\intel_a\.\code\productIC
set MkmkIF60=yes
set MkmkIF60Internal=yes
set MkmkIF90Internal=yes
set MkmkINSTALL_PATH=C:\RADER19
set MkmkMsgCatalog_PATH=C:\RADER19\intel_a\.\resources\msgcatalog
set MkmkMSNET30DIR=C:\Program Files\Reference Assemblies\Microsoft\Framework\v3.0
set MkmkMSVCADDON_INCLUDE_80=C:\Program Files (x86)\Microsoft Visual Studio 8\VC\include;C:\Program Files (x86)\Microsoft Visual Studio 8\VC\atlmfc\include;C:\Program Files (x86)\Microsoft Visual Studio 8\VC\PlatformSDK\include
set MkmkMSVCADDON_LIB_80=C:\Program Files (x86)\Microsoft Visual Studio 8\VC\lib\amd64;C:\Program Files (x86)\Microsoft Visual Studio 8\VC\atlmfc\lib\amd64;C:\Program Files (x86)\Microsoft Visual Studio 8\VC\PlatformSDK\lib\amd64
set MkmkMSVCADDON_PATH_80=C:\Program Files (x86)\Microsoft Visual Studio 8\VC\bin\amd64
set MkmkMSVCDIR=C:\Program Files (x86)\Microsoft Visual Studio 8\VC
set MkmkMSVCDIR_80=C:\Program Files (x86)\Microsoft Visual Studio 8\VC
set MkmkMSVCSHARPDIR=C:\Windows\Microsoft.NET\Framework64\v2.0.50727
set MkmkMSVJSHARPDIR=C:\Windows\Microsoft.NET\Framework64\v2.0.50727
set MkmkMSVSADDON_PATH_80=C:\Program Files (x86)\Microsoft Visual Studio 8\Common7\Tools\Bin;C:\Program Files (x86)\Microsoft Visual Studio 8\Common7\IDE
set MkmkMSVSBINDIR=C:\Program Files (x86)\Microsoft Visual Studio 8\Common7\IDE
set MkmkOrbixCpp33=yes
set MkmkOrbixCpp33Internal=yes
set MkmkOrbixJava33=yes
set MkmkOrbixJava33Internal=yes
set MkmkOS_BitMode=64
set MkmkOS_Buildtime=win_b64
set MkmkOS_DOC=DOC
set MkmkOS_NAME=Windows_NT
set MkmkOS_Runtime=intel_a
set MkmkOS_Type=Windows
set MkmkOS_VAR=win_b64
set MkmkReffiles_PATH=C:\RADER19\intel_a\.\reffiles
set MkmkRMSSDK_PATH=C:\RADER19\intel_a\.\rms\rmssdksp2
set MkmkROOT_PATH=C:\RADER19\intel_a
set MkmkSHLIB_NAME=Path
set MkmkSHLIB_PATH=C:\RADER19\intel_a\code\bin
set mkmkvers=mkmk Version 2.19.1
set MkmkVERSIONINFO=NO
set MkmkVS60=yes
set MkmkVS60Internal=yes
set MkmkVS80Internal=yes
set MkmkXMLMANIFEST=NO
set Mkmk_Modifier=554
set Mkmk_Modifier_BAD=16
set MKMK_USEPRECOMPIL=yes
set MkodtOS_Runtime=win_b64
set MK_DEVNULL=NUL
set MK_SEPARATOR=\;
set MK_TEMPDIR=C:\temp
set NO_LOCAL_DEFINITION_FOR_IID=yes
set NTsetenvPath=C:\RADER19\intel_a\code\command\
set NUMBER_OF_PROCESSORS=2
set OneDrive=C:\Users\Administrator\OneDrive
set OS=Windows_NT
set OSMFEATROOT_PATH="\\atlas\tools\osmfeat\osmfeat\"
set PATH=C:\Program Files (x86)\Microsoft Visual Studio 8\VC\bin\amd64;C:\Program Files\Reference Assemblies\Microsoft\Framework\v3.0;C:\Windows\Microsoft.NET\Framework64\v2.0.50727;C:\Program Files (x86)\Microsoft Visual Studio 8\Common7\Tools\Bin;C:\Program Files (x86)\Microsoft Visual Studio 8\Common7\IDE;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;c:\Program Files (x86)\Microsoft SQL Server\90\Tools\binn\;C:\Users\Administrator\AppData\Local\Microsoft\WindowsApps;C:\VSCode\Install\bin;C:\RADER19\intel_a\TCK\command;C:\RADER19\intel_a\code\command;C:\RADER19\intel_a\code\command;C:\RADER19\intel_a\code\command
set PATHEXT=.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC
set PROCESSOR_ARCHITECTURE=AMD64
set PROCESSOR_ARCHITEW6432=AMD64
set PROCESSOR_IDENTIFIER=Intel64 Family 6 Model 154 Stepping 3, GenuineIntel
set PROCESSOR_LEVEL=6
set PROCESSOR_REVISION=9a03
set ProgramData=C:\ProgramData
set ProgramFiles=C:\Program Files (x86)
set ProgramFiles(x86)=C:\Program Files (x86)
set ProgramW6432=C:\Program Files
set PROMPT=$P$G
set PSModulePath=C:\Program Files\WindowsPowerShell\Modules;C:\Windows\system32\WindowsPowerShell\v1.0\Modules
set PUBLIC=C:\Users\Public
set RADECATSettingPath=C:\Users\Administrator\AppData\Roaming\DassaultSystemes\RADE
set RELEASEMANAGER_PATH=C:\RADER19\intel_a
set rtcode=0
set SESSIONNAME=Console
set SystemDrive=C:
set SystemRoot=C:\Windows
set TCKHelp=-
set TCKOS_Runtime=intel_a
set TCK_DATE=2023/11/03-22:15:23
set TCK_ID=V5R19_B19
set TCK_INSTALL_PATH=C:\RADER19
set TCK_LOCAL_INFO=C:\Program Files (x86)
set TCK_NAME=V5R19_B19
set TCK_NO_SERVER=true
set TCK_ROOT_PATH=C:\RADER19\intel_a
set TCK_TMP_FILE=C:\Users\ADMINI~1\AppData\Local\Temp\tckexec__Administrator_29268.bat
set TEMP=C:\Users\ADMINI~1\AppData\Local\Temp
set TMP=C:\Users\ADMINI~1\AppData\Local\Temp
set TMPFILE=\adl_unset_22672.bat
set USERDOMAIN=DESKTOP-53K8EVV
set USERDOMAIN_ROAMINGPROFILE=DESKTOP-53K8EVV
set USERNAME=Administrator
set USERPROFILE=C:\Users\Administrator
set VBTtmp=C:\Users\ADMINI~1\AppData\Local\Temp
set VS80COMNTOOLS=C:\Program Files (x86)\Microsoft Visual Studio 8\Common7\Tools\
set WecVersionForRosebud.DA0=2
set windir=C:\Windows
set _tck_exec=OK
set __COMPAT_LAYER=ElevateCreateProcess
