set ADL_DB2INSTANCE=DB2
set ADL_DFLT_RULES_LIB=ADLCMCNextArchiRules
set ADL_DIFF_LOCAL=N
set ADL_DIFF_PATH=N/A
set ADL_MERGER="D:\RADER19\intel_a\code\command\ADLMerger2.bat"
set ADL_NLS_LANG=AMERICAN_AMERICA.WE8ISO8859P1
set ADL_ORA_TNS_ADMIN=NA
set ADL_PATH=D:\RADER19\intel_a
set ADL_SITE_NAME=V5R19_B19
set ADL_TMP=C:\TEMP
set ADL_USER_PATH=D:\RADER19\intel_a\code\command
set ALLUSERSPROFILE=C:\ProgramData
set APPDATA=C:\Users\yi.luo.EDRAWING\AppData\Roaming
set BLD_HOST_OS=win_b64
set ChocolateyInstall=C:\ProgramData\chocolatey
set CNEXTOUTPUT=console
set CommonProgramFiles=C:\Program Files (x86)\Common Files
set CommonProgramFiles(x86)=C:\Program Files (x86)\Common Files
set CommonProgramW6432=C:\Program Files\Common Files
set COMPUTERNAME=DESKTOP-SNNDI7I
set ComSpec=C:\Windows\system32\cmd.exe
set CorbaCppBuildROOT_PATH=\\ds\dsy\iona\Orbix3.3\win_b64
set CorbaCppROOT_PATH=\\ds\dsy\iona\Orbix3.3\win_b64
set CorbaJavaROOT_PATH=\\ds\dsy\iona\Orbix3.3\win_b64
set CSCSkipTestOfMapFileValidity=1
set DriverData=C:\Windows\System32\Drivers\DriverData
set DSarMakerROOT_PATH=D:\RADER19\CATWebDSarMaker
set FPS_BROWSER_APP_PROFILE_STRING=Internet Explorer
set FPS_BROWSER_USER_PROFILE_STRING=Default
set HOMEDRIVE=C:
set HOMEPATH=\Users\yi.luo.EDRAWING
set IGCCSVC_DB=AQAAANCMnd8BFdERjHoAwE/Cl+sBAAAAfO+BRbnQTUeYvtBuNADgawQAAAACAAAAAAAQZgAAAAEAACAAAAApM+MhcoqyaEPmMsajEdsT9L3otaNrwUEsRpGe7A9a6QAAAAAOgAAAAAIAACAAAABTw7MqoGIklYLWzyVDLSoZ9NbhAiQZj0wjGI3xGh3mNGAAAADO4nc9JXAJ5MUx1mUHwD8i1WyO/KLD8uuuZqxjRPnDMaYnizL8Mb4fU+sKQ+Mz+2nGfUOodIjxYGGUuA0PQ4MaTgC+92B77Iu8Lpbikb6lBnK1uMHgy3dhUKlCspWWFXlAAAAAkBaBgcYfbKF383z4i6iwjRG4N/jbOXnI1RyVLptkDPsZGCBWOY1VkN01CQi+SJKvRBr+39A3mOdNstE/aNNvCw==
set INCLUDE=D:\RADER19\intel_a\.\tools\include\win_b64;D:\RADER19\intel_a\.\tools\include;D:\VusialStudio2005\Microsoft Visual Studio 8\VC\include;D:\VusialStudio2005\Microsoft Visual Studio 8\VC\atlmfc\include;D:\VusialStudio2005\Microsoft Visual Studio 8\VC\PlatformSDK\include
set JLMDeployROOT_PATH=D:\RADER19\intel_a\jlm\jlmdeploy65
set LIB=C:\Program Files\Reference Assemblies\Microsoft\Framework\v3.0;D:\VusialStudio2005\Microsoft Visual Studio 8\VC\lib\amd64;D:\VusialStudio2005\Microsoft Visual Studio 8\VC\atlmfc\lib\amd64;D:\VusialStudio2005\Microsoft Visual Studio 8\VC\PlatformSDK\lib\amd64
set LOCALAPPDATA=C:\Users\yi.luo.EDRAWING\AppData\Local
set LOGONSERVER=\\EDRAWING-SERVER
set mkcsClientMode=1
set mkcsOS_Buildtime=intel_a
set mkcsOS_NAME=Windows_NT
set mkcsOS_Runtime=intel_a
set mkcsROOT_PATH=D:\RADER19\intel_a
set mkcsSHLIB_NAME=PATH
set mkcsSHLIB_PATH=D:\RADER19\intel_a\code\bin
set MkmkADDON_LEVEL=MK_ORBIXCPP33 MK_ORBIXJAVA33 MK_MSCVER=1400
set MkmkADDON_LIB=C:\Program Files\Reference Assemblies\Microsoft\Framework\v3.0;C:\Windows\Microsoft.NET\Framework64\v2.0.50727
set MkmkADDON_PATH=C:\Windows\Microsoft.NET\Framework64\v2.0.50727
set MkmkASPNET20Internal=yes
set MkmkBAD_MINITFLEVEL=4
set mkmkbuild=21901
set MkmkDictionary_PATH=D:\RADER19\intel_a\.\code\dictionary
set MkmkIC_PATH=D:\RADER19\intel_a\.\code\productIC
set MkmkIF60=yes
set MkmkIF60Internal=yes
set MkmkIF90Internal=yes
set MkmkINSTALL_PATH=D:\RADER19
set MkmkMsgCatalog_PATH=D:\RADER19\intel_a\.\resources\msgcatalog
set MkmkMSNET30DIR=C:\Program Files\Reference Assemblies\Microsoft\Framework\v3.0
set MkmkMSVCADDON_INCLUDE_80=D:\VusialStudio2005\Microsoft Visual Studio 8\VC\include;D:\VusialStudio2005\Microsoft Visual Studio 8\VC\atlmfc\include;D:\VusialStudio2005\Microsoft Visual Studio 8\VC\PlatformSDK\include
set MkmkMSVCADDON_LIB_80=D:\VusialStudio2005\Microsoft Visual Studio 8\VC\lib\amd64;D:\VusialStudio2005\Microsoft Visual Studio 8\VC\atlmfc\lib\amd64;D:\VusialStudio2005\Microsoft Visual Studio 8\VC\PlatformSDK\lib\amd64
set MkmkMSVCADDON_PATH_80=D:\VusialStudio2005\Microsoft Visual Studio 8\VC\bin\amd64
set MkmkMSVCDIR=D:\VusialStudio2005\Microsoft Visual Studio 8\VC
set MkmkMSVCDIR_80=D:\VusialStudio2005\Microsoft Visual Studio 8\VC
set MkmkMSVCSHARPDIR=C:\Windows\Microsoft.NET\Framework64\v2.0.50727
set MkmkMSVJSHARPDIR=C:\Windows\Microsoft.NET\Framework64\v2.0.50727
set MkmkMSVSADDON_PATH_80=D:\VusialStudio2005\Microsoft Visual Studio 8\Common7\Tools\Bin;D:\VusialStudio2005\Microsoft Visual Studio 8\Common7\IDE
set MkmkMSVSBINDIR=D:\VusialStudio2005\Microsoft Visual Studio 8\Common7\IDE
set MkmkOrbixCpp33=yes
set MkmkOrbixCpp33Internal=yes
set MkmkOrbixJava33=yes
set MkmkOrbixJava33Internal=yes
set MkmkOS_BitMode=64
set MkmkOS_Buildtime=win_b64
set MkmkOS_DOC=DOC
set MkmkOS_NAME=Windows_NT
set MkmkOS_Runtime=intel_a
set MkmkOS_Type=Windows
set MkmkOS_VAR=win_b64
set MkmkReffiles_PATH=D:\RADER19\intel_a\.\reffiles
set MkmkRMSSDK_PATH=D:\RADER19\intel_a\.\rms\rmssdksp2
set MkmkROOT_PATH=D:\RADER19\intel_a
set MkmkSHLIB_NAME=Path
set MkmkSHLIB_PATH=D:\RADER19\intel_a\code\bin
set mkmkvers=mkmk Version 2.19.1
set MkmkVERSIONINFO=NO
set MkmkVS60=yes
set MkmkVS60Internal=yes
set MkmkVS80Internal=yes
set MkmkXMLMANIFEST=NO
set Mkmk_Modifier=554
set Mkmk_Modifier_BAD=16
set MKMK_USEPRECOMPIL=yes
set MkodtOS_Runtime=win_b64
set MK_DEVNULL=NUL
set MK_SEPARATOR=\;
set MK_TEMPDIR=C:\temp
set NO_LOCAL_DEFINITION_FOR_IID=yes
set NTsetenvPath=D:\RADER19\intel_a\code\command\
set NUMBER_OF_PROCESSORS=20
set OneDrive=C:\Users\yi.luo.EDRAWING\OneDrive
set OS=Windows_NT
set OSMFEATROOT_PATH="\\atlas\tools\osmfeat\osmfeat\"
set PATH=D:\VusialStudio2005\Microsoft Visual Studio 8\VC\bin\amd64;C:\Program Files\Reference Assemblies\Microsoft\Framework\v3.0;C:\Windows\Microsoft.NET\Framework64\v2.0.50727;D:\VusialStudio2005\Microsoft Visual Studio 8\Common7\Tools\Bin;D:\VusialStudio2005\Microsoft Visual Studio 8\Common7\IDE;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files\dotnet\;C:\Program Files\Microsoft\Web Platform Installer\;C:\Program Files (x86)\Microsoft ASP.NET\ASP.NET Web Pages\v1.0\;C:\Program Files\Microsoft SQL Server\110\Tools\Binn\;C:\ProgramData\chocolatey\bin;C:\Program Files\CMake\bin;C:\Program Files (x86)\Microsoft SQL Server\90\Tools\binn\;D:\Git\Install\cmd;C:\Anaconda\Install\Scripts;C:\Anaconda\Install\Library\bin;C:\Anaconda\Install\Library\mingw-w64\bin;C:\Anaconda\Install\Library\usr\bin;C:\Anaconda\Install;C:\Program Files\Pandoc\;D;C:\Users\yi.luo.EDRAWING\AppData\Local\Microsoft\WindowsApps;C:\Users\yi.luo.EDRAWING\AppData\Local\Programs\Microsoft VS Code\bin;D:\RADER19\intel_a\TCK\command;D:\RADER19\intel_a\code\command;D:\RADER19\intel_a\code\command;D:\RADER19\intel_a\code\command
set PATHEXT=.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC
set PROCESSOR_ARCHITECTURE=AMD64
set PROCESSOR_ARCHITEW6432=AMD64
set PROCESSOR_IDENTIFIER=Intel64 Family 6 Model 154 Stepping 3, GenuineIntel
set PROCESSOR_LEVEL=6
set PROCESSOR_REVISION=9a03
set ProgramData=C:\ProgramData
set ProgramFiles=C:\Program Files (x86)
set ProgramFiles(x86)=C:\Program Files (x86)
set ProgramW6432=C:\Program Files
set PROMPT=$P$G
set PSModulePath=C:\Program Files\WindowsPowerShell\Modules;C:\Windows\system32\WindowsPowerShell\v1.0\Modules
set PUBLIC=C:\Users\Public
set RADECATSettingPath=C:\Users\yi.luo.EDRAWING\AppData\Roaming\DassaultSystemes\RADE
set RELEASEMANAGER_PATH=D:\RADER19\intel_a
set rtcode=0
set SESSIONNAME=Console
set SystemDrive=C:
set SystemRoot=C:\Windows
set TCKHelp=-
set TCKOS_Runtime=intel_a
set TCK_DATE=2024/05/06-14:49:52
set TCK_ID=V5R19_B19
set TCK_INSTALL_PATH=D:\RADER19
set TCK_LOCAL_INFO=C:\Program Files (x86)
set TCK_NAME=V5R19_B19
set TCK_NO_SERVER=true
set TCK_ROOT_PATH=D:\RADER19\intel_a
set TCK_TMP_FILE=C:\Users\YILUO~1.EDR\AppData\Local\Temp\tckexec__yi.luo_39365.bat
set TEMP=C:\Users\YILUO~1.EDR\AppData\Local\Temp
set TMP=C:\Users\YILUO~1.EDR\AppData\Local\Temp
set TMPFILE=\adl_unset_13703.bat
set USERDNSDOMAIN=EDRAWING.CN
set USERDOMAIN=EDRAWING
set USERDOMAIN_ROAMINGPROFILE=EDRAWING
set USERNAME=yi.luo
set USERPROFILE=C:\Users\yi.luo.EDRAWING
set VBTtmp=C:\Users\YILUO~1.EDR\AppData\Local\Temp
set VS110COMNTOOLS=C:\Program Files (x86)\Microsoft Visual Studio 11.0\Common7\Tools\
set VS140COMNTOOLS=C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\Tools\
set VS80COMNTOOLS=D:\VusialStudio2005\Microsoft Visual Studio 8\Common7\Tools\
set WecVersionForRosebud.700C=2
set windir=C:\Windows
set ZES_ENABLE_SYSMAN=1
set _tck_exec=OK
set __COMPAT_LAYER=ElevateCreateProcess
set __PSLockDownPolicy=0
