set ADL_DB2INSTANCE=DB2
set ADL_DFLT_RULES_LIB=ADLCMCNextArchiRules
set ADL_DIFF_LOCAL=N
set ADL_DIFF_PATH=N/A
set ADL_MERGER="C:\RADE\intel_a\code\command\ADLMerger2.bat"
set ADL_NLS_LANG=AMERICAN_AMERICA.WE8ISO8859P1
set ADL_ORA_TNS_ADMIN=NA
set ADL_PATH=C:\RADE\intel_a
set ADL_SITE_NAME=V5R18_B18
set ADL_TMP=C:\TEMP
set ADL_USER_PATH=C:\RADE\intel_a\code\command
set ALLUSERSPROFILE=C:\ProgramData
set APPDATA=C:\Users\Administrator\AppData\Roaming
set BLD_HOST_OS=win_b64
set CommonProgramFiles=C:\Program Files (x86)\Common Files
set CommonProgramFiles(x86)=C:\Program Files (x86)\Common Files
set CommonProgramW6432=C:\Program Files\Common Files
set COMPUTERNAME=DESKTOP-TFJD45J
set ComSpec=C:\WINDOWS\system32\cmd.exe
set CorbaCppBuildROOT_PATH=\\lisa\iona\Orbix3.3\win_b64
set CorbaCppROOT_PATH=\\lisa\iona\Orbix3.3\win_b64
set CorbaJavaROOT_PATH=\\lisa\iona\Orbix3.3\win_b64
set CSCSkipTestOfMapFileValidity=1
set DriverData=C:\Windows\System32\Drivers\DriverData
set DSarMakerROOT_PATH=C:\RADE\CATWebDSarMaker
set FPS_BROWSER_APP_PROFILE_STRING=Internet Explorer
set FPS_BROWSER_USER_PROFILE_STRING=Default
set HOMEDRIVE=C:
set HOMEPATH=\Users\Administrator
set INCLUDE=C:\RADE\intel_a\tools\include\win_b64;C:\RADE\intel_a\tools\include;C:\Program Files (x86)\Microsoft Visual Studio 8\VC\include;C:\Program Files (x86)\Microsoft Visual Studio 8\VC\atlmfc\include;C:\Program Files (x86)\Microsoft Visual Studio 8\VC\PlatformSDK\include
set Java1ROOT_PATH=C:\jdk1.1.8
set Java3ROOT_PATH=C:\jdk1.3.1_08
set JAVA_HOME=C:\Program Files\Java\jdk1.8.0_351
set JLMDeployROOT_PATH=C:\RADE\intel_a\jlm\jlmdeploy65
set KMP_DUPLICATE_LIB_OK=TRUE
set LIB=C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\v3.0;C:\Program Files (x86)\Microsoft Visual Studio 8\VC\lib\amd64;C:\Program Files (x86)\Microsoft Visual Studio 8\VC\atlmfc\lib\amd64;C:\Program Files (x86)\Microsoft Visual Studio 8\VC\PlatformSDK\lib\amd64
set LOCALAPPDATA=C:\Users\Administrator\AppData\Local
set LOGONSERVER=\\DESKTOP-TFJD45J
set mkcsClientMode=1
set mkcsOS_Buildtime=intel_a
set mkcsOS_NAME=Windows_NT
set mkcsOS_Runtime=intel_a
set mkcsROOT_PATH=C:\RADE\intel_a
set mkcsSHLIB_NAME=PATH
set mkcsSHLIB_PATH=C:\RADE\intel_a\code\bin
set MkmkADDON_LEVEL=MK_ORBIXCPP33 MK_ORBIXJAVA33 MK_MSCVER=1400
set MkmkADDON_LIB=C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\v3.0;C:\Windows\Microsoft.NET\Framework64\v2.0.50727
set MkmkADDON_PATH=C:\Windows\Microsoft.NET\Framework64\v2.0.50727
set MkmkASPNET20Internal=yes
set mkmkbuild=21803
set MkmkDictionary_PATH=C:\RADE\intel_a\code\dictionary
set MkmkIC_PATH=C:\RADE\intel_a\code\productIC
set MkmkIF60=yes
set MkmkIF60Internal=yes
set MkmkIF90Internal=yes
set MkmkINSTALL_PATH=C:\RADE
set MkmkMsgCatalog_PATH=C:\RADE\intel_a\resources\msgcatalog
set MkmkMSNET30DIR=C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\v3.0
set MkmkMSVCADDON_INCLUDE_80=C:\Program Files (x86)\Microsoft Visual Studio 8\VC\include;C:\Program Files (x86)\Microsoft Visual Studio 8\VC\atlmfc\include;C:\Program Files (x86)\Microsoft Visual Studio 8\VC\PlatformSDK\include
set MkmkMSVCADDON_LIB_80=C:\Program Files (x86)\Microsoft Visual Studio 8\VC\lib\amd64;C:\Program Files (x86)\Microsoft Visual Studio 8\VC\atlmfc\lib\amd64;C:\Program Files (x86)\Microsoft Visual Studio 8\VC\PlatformSDK\lib\amd64
set MkmkMSVCADDON_PATH_80=C:\Program Files (x86)\Microsoft Visual Studio 8\VC\bin\amd64
set MkmkMSVCDIR=C:\Program Files (x86)\Microsoft Visual Studio 8\VC
set MkmkMSVCDIR_80=C:\Program Files (x86)\Microsoft Visual Studio 8\VC
set MkmkMSVCSHARPDIR=C:\Windows\Microsoft.NET\Framework64\v2.0.50727
set MkmkMSVJSHARPDIR=C:\Windows\Microsoft.NET\Framework64\v2.0.50727
set MkmkMSVSADDON_PATH_80=C:\Program Files (x86)\Microsoft Visual Studio 8\Common7\Tools\Bin;C:\Program Files (x86)\Microsoft Visual Studio 8\Common7\IDE
set MkmkMSVSBINDIR=C:\Program Files (x86)\Microsoft Visual Studio 8\Common7\IDE
set MkmkOrbixCpp33=yes
set MkmkOrbixCpp33Internal=yes
set MkmkOrbixJava33=yes
set MkmkOrbixJava33Internal=yes
set MkmkOS_BitMode=64
set MkmkOS_Buildtime=win_b64
set MkmkOS_DOC=DOC
set MkmkOS_NAME=Windows_NT
set MkmkOS_Runtime=intel_a
set MkmkOS_Type=Windows
set MkmkOS_VAR=win_b64
set MkmkReffiles_PATH=C:\RADE\intel_a\reffiles
set MkmkRMSSDK_PATH=C:\RADE\intel_a\.\rms\rmssdksp2
set MkmkROOT_PATH=C:\RADE\intel_a
set MkmkSHLIB_NAME=Path
set MkmkSHLIB_PATH=C:\RADE\intel_a\code\bin
set mkmkvers=mkmk Version 2.18.3
set MkmkVERSIONINFO=NO
set MkmkVS60=yes
set MkmkVS60Internal=yes
set MkmkVS80Internal=yes
set MkmkXMLMANIFEST=NO
set MKMK_JAVAC_CMD_SIZE=32000
set Mkmk_Modifier=1034
set MKMK_NO_MONOCODE_DOC=yes
set MKMK_USEPRECOMPIL=yes
set MkodtOS_Runtime=win_b64
set MK_DEVNULL=NUL
set MK_SEPARATOR=\;
set MK_TEMPDIR=C:\temp
set NEO4J_HOME=C:\TypicalComponent\neo4j-community-3.4.5
set NO_LOCAL_DEFINITION_FOR_IID=yes
set NTsetenvPath=C:\RADE\intel_a\code\command\
set NUMBER_OF_PROCESSORS=8
set OneDrive=C:\Users\Administrator\OneDrive
set OS=Windows_NT
set OSMFEATROOT_PATH="\\atlas\tools\osmfeat\osmfeat\"
set PATH=C:\Program Files (x86)\Microsoft Visual Studio 8\VC\bin\amd64;C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\v3.0;C:\Windows\Microsoft.NET\Framework64\v2.0.50727;C:\Program Files (x86)\Microsoft Visual Studio 8\Common7\Tools\Bin;C:\Program Files (x86)\Microsoft Visual Studio 8\Common7\IDE;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\Java\jdk1.8.0_351\bin;C:\TypicalComponent\neo4j-community-3.4.5\bin;C:\Program Files\Microsoft\Web Platform Installer\;C:\Program Files (x86)\Microsoft ASP.NET\ASP.NET Web Pages\v1.0\;C:\Program Files\Microsoft SQL Server\110\Tools\Binn\;c:\Program Files (x86)\Microsoft SQL Server\90\Tools\binn\;C:\Users\Administrator\AppData\Local\Programs\Python\Python310\Scripts\;C:\Users\Administrator\AppData\Local\Programs\Python\Python310\;C:\Users\Administrator\AppData\Local\Microsoft\WindowsApps;C:\WINDOWS\System32\Wbem;C:\RADE\intel_a\TCK\command;C:\RADE\intel_a\code\command;C:\RADE\intel_a\code\command;C:\RADE\intel_a\code\command
set PATHEXT=.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC
set PROCESSOR_ARCHITECTURE=x86
set PROCESSOR_ARCHITEW6432=AMD64
set PROCESSOR_IDENTIFIER=Intel64 Family 6 Model 158 Stepping 9, GenuineIntel
set PROCESSOR_LEVEL=6
set PROCESSOR_REVISION=9e09
set ProgramData=C:\ProgramData
set ProgramFiles=C:\Program Files (x86)
set ProgramFiles(x86)=C:\Program Files (x86)
set ProgramW6432=C:\Program Files
set PROMPT=$P$G
set PSModulePath=C:\Program Files\WindowsPowerShell\Modules;C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules
set PUBLIC=C:\Users\Public
set RADECATSettingPath=C:\Users\Administrator\AppData\Roaming\DassaultSystemes\RADE
set RELEASEMANAGER_PATH=C:\RADE\intel_a
set rtcode=0
set SESSIONNAME=Console
set SystemDrive=C:
set SystemRoot=C:\WINDOWS
set TCKHelp=-
set TCKOS_Runtime=intel_a
set TCK_DATE=2024/06/30-13:59:51
set TCK_ID=V5R18_B18
set TCK_INSTALL_PATH=C:\RADE
set TCK_LOCAL_INFO=C:\Program Files (x86)
set TCK_NAME=V5R18_B18
set TCK_NO_SERVER=true
set TCK_ROOT_PATH=C:\RADE\intel_a
set TCK_TMP_FILE=C:\Users\ADMINI~1\AppData\Local\Temp\tckexec__Administrator_29573.bat
set TEMP=C:\Users\ADMINI~1\AppData\Local\Temp
set TMP=C:\Users\ADMINI~1\AppData\Local\Temp
set TMPFILE=\adl_unset_21645.bat
set USERDOMAIN=DESKTOP-TFJD45J
set USERDOMAIN_ROAMINGPROFILE=DESKTOP-TFJD45J
set USERNAME=Administrator
set USERPROFILE=C:\Users\Administrator
set VBTtmp=C:\Users\ADMINI~1\AppData\Local\Temp
set VS110COMNTOOLS=C:\Program Files (x86)\Microsoft Visual Studio 11.0\Common7\Tools\
set VS140COMNTOOLS=C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\Tools\
set VS80COMNTOOLS=C:\Program Files (x86)\Microsoft Visual Studio 8\Common7\Tools\
set WecVersionForRosebud.1994=2
set windir=C:\WINDOWS
set _tck_exec=OK
set __COMPAT_LAYER=ElevateCreateProcess
set __PSLockDownPolicy=0
